### ISSUE TITLE
Host monitoring - improve host monitoring expressions to be resistant in case of IP address miss configuration 

### ISSUE THREAD

**Issue by matofeder** [dNationCloud/kubernetes-monitoring#100]
# Description

After IP addresses miss configuration some expressions stop work with error message:
```
"found duplicate series for the match group {instance=\"35.187.16.73:9100\"} on the right hand-side of the operation: [{__name__=\"node_uname_info\", alertGroup=\"Host\", domainname=\"(none)\", endpoint=\"9100\", instance=\"35.187.16.73:9100\", job=\"prod-sql-2\", machine=\"x86_64\", namespace=\"monitoring\", nodename=\"prod-lb-9wpv\", release=\"5.4.0-1040-gcp\", service=\"dnation-kubernetes-monitoring-stack-prod-sql-2-prod-sql-2\", sysname=\"Linux\", version=\"#43-Ubuntu SMP Fri Mar 19 17:49:48 UTC 2021\"}, {__name__=\"node_uname_info\", alertGroup=\"Host\", domainname=\"(none)\", endpoint=\"9100\", instance=\"35.187.16.73:9100\", job=\"prod-lb-9wpv\", machine=\"x86_64\", namespace=\"monitoring\", nodename=\"prod-lb-9wpv\", release=\"5.4.0-1040-gcp\", service=\"dnation-kubernetes-monitoring-stack-prod-lb-9wpv-prod-lb-9wpv\", sysname=\"Linux\", version=\"#43-Ubuntu SMP Fri Mar 19 17:49:48 UTC 2021\"}];many-to-many matching not allowed: matching labels must be unique on one side"
```

Above state is caused by following configuration:

```
hostMonitoring:
    - name: prod-sql-2
      jobName: prod-sql-2
      host:
        address: 35.187.16.73
 ...
    - name: prod-lb-9wpv
      jobName: prod-lb-9wpv
      host:
        address: 35.187.16.73
...
```

Example of affected expression:
```
avg(round((1 - (avg(irate(node_cpu_seconds_total{cluster=~"$cluster|", job=~"$job", mode="idle"}[5m]) * on(instance) group_left(nodename) (node_uname_info)) by (job, nodename) )) * 100))
```
Duplicate series were found because we want to group_left `nodename` label based on `instance` label.

# Possible solution

Possible solution is to add another common label to the `on` directive e.g. `on(instance, job)`

# Actions

- [x] Try to reproduce above scenario
- [x] Fix all affected expressions
